	spring.application.name=mejor-project-techno

server.port=${PORT:9089}

# MySQL Database Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/techno_cms
#spring.datasource.username=root
#spring.datasource.password=root
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:20326/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=NqzWHUlVXZnIdVmjeibTrGljmjIiYODW
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB